### ISSUE TITLE
can't see blue dot behind red dot

### ISSUE THREAD

**Issue by tdhock** [Anirban166/data.table.threads#29]
hi @Anirban166 

I see on README 

![image](https://github.com/user-attachments/assets/536e56b9-c6ec-4f74-aa11-2ab8352e9c04)

Above is potentially confusing for forder because the two dots are exactly the same size. can you please reduce the size of red dot, so that we can see the blue dot behind it?

**Comment by Anirban166** [comment]
Great point! I made [the changes]() for it but I'll need to update the readme after being able to run that code within a reasonable amount of time (I just noticed that the code runs much slower for `rowCount` > 1e3 with `colCount` set to 10 - It seems I introduced a performance bottleneck in #28, since this wasn't the case before I integrated that PR; I will file a new issue)

**Comment by Anirban166** [comment]
Great point! I made [the changes](https://github.com/Anirban166/data.table.threads/commits?author=Anirban166&since=2024-12-03&until=2024-12-04) for it but I'll need to update the readme after being able to run that code within a reasonable amount of time (I just noticed that the code runs much slower for `rowCount` > 1e3 with `colCount` set to 10 - It seems I introduced a performance bottleneck in #28, since this wasn't the case before I integrated that PR; I will file a new issue)

**Comment by Anirban166** [comment]
Actually nevermind (ignore what I said), it was an issue with my R session..

**Comment by Anirban166** [comment]
Great point! I made [the changes](https://github.com/Anirban166/data.table.threads/commits?author=Anirban166&since=2024-12-03&until=2024-12-04) for it but I'll need to update the readme after being able to run that code within a reasonable amount of time (I just noticed that the code runs much slower for `rowCount` > 1e3 with `colCount` set to 10 - It seems I introduced a performance bottleneck in #28, since this wasn't the case before I integrated that PR; I will file a new issue)

**Comment by Anirban166** [comment]
Great point! I made [the changes](https://github.com/Anirban166/data.table.threads/commits?author=Anirban166&since=2024-12-03&until=2024-12-04) for it but I'll need to update the readme after being able to run that code within a reasonable amount of time (I just noticed via `Rprof` that `findOptimalThreadCount` or in turn `runBenchmarks` runs much slower - It seems I introduced a performance bottleneck in #28, since this wasn't the case before; I filed an [issue](#30))

**Comment by Anirban166** [comment]
Great point! I made [the changes](https://github.com/Anirban166/data.table.threads/commits?author=Anirban166&since=2024-12-03&until=2024-12-04) for it but I'll need to update the readme after being able to run that code within a reasonable amount of time (I just noticed via `Rprof` that `findOptimalThreadCount` or in turn `runBenchmarks` runs much slower - It seems I introduced a performance bottleneck in #28, since this wasn't the case before; I filed an [issue](https://github.com/Anirban166/data.table.threads/issues/30))

**Comment by Anirban166** [comment]
Great point! I made [the changes](https://github.com/Anirban166/data.table.threads/commits?author=Anirban166&since=2024-12-03&until=2024-12-04) in code for resolving this but I'll need to update the readme after being able to run my function within a reasonable amount of time as I noticed that `findOptimalThreadCount` (or in turn `runBenchmarks`) runs much slower (was testing via `Rprof` a while ago) - It seems I introduced a performance bottleneck in #28 since this wasn't the case before (I filed a separate [issue](https://github.com/Anirban166/data.table.threads/issues/30) for that)

**Comment by Anirban166** [comment]
@tdhock Here's how it looks like now: (another example where both ideal and recommended thread count values for forder are at 8)
```r
(benchmarks <- findOptimalThreadCount(1e6, 10))
benchmarks_r <- addRecommendedEfficiency(benchmarks, recommendedEfficiency = 0.4)
plot(benchmarks_r)
```
```
function             Thread count Fastest median runtime (ms)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
forder               8            9325.798500            
GForce_sum           5            1828.866500            
subsetting           9            4328.472500            
frollmean            2            2243.704500            
fcoalesce            5            738.369000             
between              6            2139.441500            
fifelse              5            1696.149500            
nafill               2            615.635500             
CJ                   1            454.444000  
```
<img width="869" alt="image" src="https://github.com/user-attachments/assets/85fe2ebe-7765-43ca-8679-eac1bc05208d">

**Comment by tdhock** [comment]
great thx
